"""Add currency attribute to visaInfo table to db

Revision ID: 2c99ef9f2ca5
Revises: 418ac0d14f95
Create Date: 2024-07-15 21:06:28.732746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c99ef9f2ca5'
down_revision = '418ac0d14f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.alter_column('visa_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('validity_period',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('processing_time',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('cost',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('application_method',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('entry_frequency',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('visa_purpose',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_info', schema=None) as batch_op:
        batch_op.alter_column('visa_purpose',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('entry_frequency',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('application_method',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('processing_time',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('validity_period',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('visa_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
