"""Add visaInfo table to db

Revision ID: 418ac0d14f95
Revises: d30553741175
Create Date: 2024-07-15 20:54:22.296418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418ac0d14f95'
down_revision = 'd30553741175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=False),
    sa.Column('destination_country', sa.String(length=64), nullable=False),
    sa.Column('visa_type', sa.String(length=64), nullable=False),
    sa.Column('validity_period', sa.String(length=64), nullable=False),
    sa.Column('processing_time', sa.String(length=64), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('application_method', sa.String(length=64), nullable=False),
    sa.Column('entry_frequency', sa.String(length=64), nullable=False),
    sa.Column('visa_purpose', sa.String(length=64), nullable=False),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visa_info')
    # ### end Alembic commands ###
