"""modify user info db

Revision ID: d30553741175
Revises: 28b996a7803e
Create Date: 2024-07-14 16:02:23.743355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30553741175'
down_revision = '28b996a7803e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=False),
    sa.Column('destination_country', sa.String(length=64), nullable=False),
    sa.Column('purpose_of_visit', sa.String(length=64), nullable=True),
    sa.Column('duration_of_stay', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user_info')
    # ### end Alembic commands ###
